/**
 * Shared constants and DOM selectors specific to the content script environment.
 */
import { MESSAGE_SELECTORS, MESSAGE_SELECTOR } from './selectors.js';
import {
  LANGUAGE_HINT_DEFAULT,
  LANGUAGE_HINT_MESSAGE_TYPE,
  LANGUAGE_DETECTION_MAX_MESSAGES,
  LANGUAGE_DETECTION_MAX_CHARS,
  LANGUAGE_DETECTION_CACHE_INTERVAL
} from '../common/constants.js';

export { MESSAGE_SELECTORS, MESSAGE_SELECTOR };

export const PERSIAN_CHAR_REGEX = /[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/;

export {
  LANGUAGE_HINT_DEFAULT,
  LANGUAGE_HINT_MESSAGE_TYPE,
  LANGUAGE_DETECTION_MAX_MESSAGES,
  LANGUAGE_DETECTION_MAX_CHARS,
  LANGUAGE_DETECTION_CACHE_INTERVAL
};
